version: '3.8'

services:
  apigateway:
    build: ./docker/apigateway
    ports:
      - '8080:8080'
    networks:
      - frontend
      - backend

  cloudwatch:
    build: ./docker/cloudwatch
    volumes:
      - metrics_data:/var/lib/cloudwatch
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  metrics_data:
