name: aws-local-infrastructure

services:
  apigateway:
    build: 
      context: ./docker/apigateway
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - frontend
      - backend
    volumes:
      - ./docker/apigateway/src:/usr/src/app/src

  bedrock:
    build: 
      context: ./docker/bedrock
      dockerfile: Dockerfile
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - TRANSFORMERS_CACHE=/root/.cache/huggingface
      - CUDA_VISIBLE_DEVICES=0
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
      - MODEL_BASE_PATH=/models
      - MODEL_CONFIG_PATH=/models/config
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - '5000:5000'
    networks:
      - backend
    volumes:
      - ./docker/bedrock/src:/usr/src/app/src
      - ./storage/models:/models
      - ./storage/cache:/root/.cache/huggingface
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  cloudwatch:
    build:
      context: ./docker/cloudwatch
      dockerfile: Dockerfile
    volumes:
      - ./docker/cloudwatch/src:/usr/src/app/src
      - ./storage/cloudwatch:/var/lib/cloudwatch
    networks:
      - backend
    ports:
      - '9090:9090'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge